import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Senior Software Engineer Full-Stack',
    company: 'PetSmart',
    company_legal_name: 'PetSmart.',
    logo: null,
    location: 'Costa Rica 🇨🇷',
    location_type: 'Hybrid',
    type: 'Full-time',
    start_date: '2025-06',
    end_date: null,
    industry: 'technology',
    link: 'https://www.encora.com',
    responsibilities: [
      'Analyze business requirements, provide accurate development estimates, offer experience-based feedback, and help determine the proper implementation',
      'Collaborate on the migration to a new monolithic microservices architecture',
      'Build highly performant web applications using TDD and 12-factor app practices',
    ],
  },
  {
    position: 'Senior Software Engineer Front-End',
    company: 'Encora',
    company_legal_name: 'Encora Inc.',
    logo: null,
    location: 'Costa Rica 🇨🇷',
    location_type: 'Hybrid',
    type: 'Full-time',
    start_date: '2020-11',
    end_date: '2025-03',
    industry: 'technology',
    link: 'https://www.encora.com',
    responsibilities: [
      'Successfully migrated a legacy codebase built with React class components and vanilla JavaScript to a modern stack using Next.js and TypeScript, integrating GraphQL queries for efficient data fetching.',
      'Used v0.dev by Vercel for rapid prototyping of user interfaces.',
      'Collaborated with the backend team to create new API endpoints for new features using Django and PostgreSQL.',
      'Developed and constructed reusable Next.JS components incorporating modern UI framework\'s best practices.',
    ],
  },
  {
    position: 'Senior Web Developer',
    company: 'Gorilla Logic',
    company_legal_name: 'Gorilla Logic Inc.',
    logo: null,
    location: 'Costa Rica 🇨🇷',
    location_type: 'Hybrid',
    type: 'Full-time',
    start_date: '2020-02',
    end_date: '2020-11',
    industry: 'technology',
    link: 'https://gorillalogic.com',
    responsibilities: [
      'Overhauled the UI for an internal tool for the HR department to extract and save data from PDFs, which helped the HR team improve the recruiting process by 20%.',
      'Developed a cutting-edge UI React.js application for dispatch management, utilizing advanced technologies and creating a JSON server mock for early development stages.',
      'Contributed to implementing RESTful APIs in NodeJS/Express with another developer.',
    ],
  },
  {
    position: 'Software Front-End Developer',
    company: 'Avantica (Now Encora)',
    company_legal_name: 'Avantica Technologies',
    logo: null,
    location: 'Costa Rica 🇨🇷',
    location_type: 'Remote',
    type: 'Contractor',
    start_date: '2018-08',
    end_date: '2020-02',
    industry: 'technology',
    link: 'https://www.encora.com',
    responsibilities: [
      'Built new features for the new UI dashboard of an e-commerce web application, which was reaching over 100,000 users monthly.',
      'Integrated the RESTful API with the frontend application built with Angular.',
      'Conducted regular code reviews and implemented code quality improvements, leading to a 30% decrease in bugs reported by users and a better user experience.',
    ],
  },
  {
    position: 'Front-end Engineer',
    company: 'DotCMS',
    company_legal_name: 'dotCMS LLC',
    logo: null,
    location: 'Miami - Costa Rica 🇺🇸🇨🇷',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2017-08',
    end_date: '2018-05',
    industry: 'technology',
    link: 'https://www.dotcms.com',
    responsibilities: [
      'Collaborated to convert existing user UIs to Angular 4+ and optimize for speed and scalability. The app performance improved by 20% due to teamwork.',
      'Designed user interfaces in Angular 4+ with enhanced functionality.',
      'Collaborated with agile team members and product owners to create and estimate new tasks.',
    ],
  },
  {
    position: 'Front-end Developer',
    company: 'Prodigious',
    company_legal_name: 'Prodigious Latin America',
    logo: null,
    location: 'Costa Rica 🇨🇷',
    location_type: 'Onsite',
    type: 'Full-time',
    start_date: '2016-12',
    end_date: '2017-08',
    industry: 'digital agency',
    link: 'https://www.prodigious.com',
    responsibilities: [
      'Built and maintained components using React, Express, HTML5, and Sass.',
      'Collaborated closely with a fellow developer to architect an internal web application tool to streamline customer refunds. The app was an NX monorepo with React.js on the front end and Express with MongoDB on the backend.',
    ],
  },
  {
    position: 'CMS Tech Lead & Web Developer',
    company: 'Hangar',
    company_legal_name: 'Hangar Worldwide',
    logo: null,
    location: 'Costa Rica 🇨🇷',
    location_type: 'Onsite',
    type: 'Full-time',
    start_date: '2015-10',
    end_date: '2016-12',
    industry: 'digital agency',
    link: null,
    responsibilities: [
      'Spearheaded sprint planning initiatives, story estimation, task allocation, and improved team velocity.',
      'Guided CMS expertise in collaborative web content planning with business and development teams.',
    ],
  },
  {
    position: 'Web Developer',
    company: 'Accenture',
    company_legal_name: 'Accenture S.R.L',
    logo: null,
    location: 'Costa Rica 🇨🇷',
    location_type: 'Onsite',
    type: 'Full-time',
    start_date: '2012-09',
    end_date: '2015-10',
    industry: 'consulting',
    link: 'https://www.accenture.com',
    responsibilities: [
      'Transformed PSD comps into pixel-perfect designs, ensuring seamless integration with front-end development.',
      'Social media integration, including Facebook Share, Facebook Like, Twitter Share, and YouTube.',
      'Implemented tracking analytics across the entire platform.',
    ],
  },
];
