import { ProjectItemProps } from '../types/projects';

export const PROJECTS: ProjectItemProps[] = [
  {
    title: 'Personal Portfolio Website',
    slug: 'personal-portfolio',
    description: 'A modern, responsive portfolio built with Next.js, TypeScript, and Tailwind CSS. Features dark mode, animations, and optimized performance.',
    image: '/images/projects/portfolio-site.png',
    link_demo: 'https://luisrojascr',
    link_github: 'https://github.com/luisrojascr/my-portfolio',
    stacks: '["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"]',
    content: 'A comprehensive portfolio website showcasing projects, skills, and experience. Built with modern web technologies and best practices.',
    is_show: true,
    is_featured: true,
    updated_at: new Date('2024-01-15'),
  },
  {
    title: 'ISSA E-Commerce Platform',
    slug: 'issa-ecommerce-platform',
    description: 'ISSA Online is the public-facing e-learning and e-commerce site of the International Sports Sciences Association.',
    image: '/images/projects/issaonline-site.png',
    link_demo: 'https://www.issaonline.com/',
    link_github: '',
    stacks: '["Next.js", "TypeScript", "Chakra UI ", "Styled-Components", "ContentFul", "Elastic Path"]',
    content: 'A React/Next.js front-end styled with Chakra UI, typed in TypeScript and built with TDD. Pages are served through an Apache HTTP Server that hands off assets to the Akamai CDN for global edge caching.',
    is_show: true,
    is_featured: false,
    updated_at: new Date('2023-12-20'),
  },
  {
    title: 'Antimatter',
    slug: 'weather-dashboard',
    description: 'Antimatter (antimatter.io) is developing a new product to help people securely manage customer data while creating AI features using LLMs. ',
    image: '/images/projects/antimatter-dashboard.png',
    link_demo: 'https://app.antimatter.io/dashboard',
    link_github: '',
    stacks: '["TypeScript", "React", "JavaScript", "Jest", "Material-UI", "Next.js", "Styled-Components", "Playwright"]',
    content: 'This product consists primarily of libraries and services that SaaS companies can use to classify, encrypt, and enforce data governance policies for customer data.',
    is_show: true,
    is_featured: true,
    updated_at: new Date('2023-10-05'),
  },
  {
    title: 'Molekule',
    slug: 'molekule-app',
    description: 'The Admin portal dashboard for Molekule is a sophisticated web application I developed using Angular and Ngx-admin',
    image: '/images/projects/molekule.png',
    link_demo: 'https://map-dev.molekule.com/',
    link_github: '',
    stacks: '["Angular", "TypeScript", "RxJS", "ES6", "NGX-Admin", "AWS Cognito"]',
    content: "The Admin portal dashboard for Molekule is a sophisticated web application I developed using Angular and Ngx-admin. It features robust user authentication managed through AWS Cognito. For a hands-on experience, you're welcome to set up a test account or contact me for access to a demo account.",
    is_show: true,
    is_featured: false,
    updated_at: new Date('2023-09-15'),
  },
  {
    title: 'Minerva App',
    slug: 'minerva-app',
    description: 'Real-time cryptocurrency price tracker with portfolio management, price alerts, and market analysis tools.',
    image: '/images/projects/minerva.png',
    link_demo: 'https://minerva-platform.herokuapp.com/',
    link_github: '',
    stacks: '["Angular", "TypeScript", "RxJS", "Sass", "Material Design", "AWS Cognito"]',
    content: 'I developed a data-focused web application for a client named Minerva Data, tailored to offer comprehensive data insights specifically for Costa Rican companies. Originally hosted on Heroku, this project, while no longer actively maintained, showcased a robust platform for data analysis and visualization.',
    is_show: true,
    is_featured: false,
    updated_at: new Date('2023-08-20'),
  },
  {
    title: 'Vanity Spa',
    slug: 'vanity-spa',
    description: 'Mobile-first recipe discovery app with ingredient-based search, nutritional information, and meal planning features.',
    image: '/images/projects/portfolio-vanityspa.png',
    link_demo: 'https://vanityspacostarica.com/',
    link_github: '',
    stacks: '["WordPress", "PHP", "HTML", "CSS"]',
    content: 'A recipe discovery app that helps users find recipes based on available ingredients and dietary preferences.',
    is_show: true,
    is_featured: false,
    updated_at: new Date('2023-07-12'),
  },
  {
    title: 'Rumbo Económico',
    slug: 'rumbo-economico',
    description: 'WordPress site for Rumbo Económico, a Costa Rican news portal.',
    image: '/images/projects/portfolio-rumbo-economico.png',
    link_demo: 'https://rumboeconomico.net/',
    link_github: '',
    stacks: '["WordPress", "PHP", "HTML", "CSS"]',
    content: 'A powerful analytics tool for social media professionals to track performance and optimize their content strategy.',
    is_show: true,
    is_featured: false,
    updated_at: new Date('2023-06-08'),
  },
];
